[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['npm i tar','npm i discord.js@dev','npm install -g npm ','npm install --omit=dev','npm ci']

[phases.build]
cmds = ["echo building!"]
cmd = ['npm run build']


