[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['npm cache clean --force','npm install -g npm@7.6.0', 'npm install','npm start']

[phases.build]
cmds = ["echo building!"]
cmd = ['npm run build']


